#!/usr/bin/bash

######################################
# POST http://localhost:8888/customer
# Content-Type: application/json
# {
#     "firstName": "Jane",
#     "lastName": "Smith",
#     "email": "jane.smith@plexus"
# }
######################################
curl --header "Content-Type: application/json" -d "{\"firstName\":\"Jane\",\"lastName\":\"Smith\",\"email\":\"jane.smith@plexus\"}" http://localhost:8888/customer

######################################
# POST http://localhost:8888/customer
# Content-Type: application/json
# {
#     "firstName": "John",
#     "lastName": "Smith",
#     "email": "john.smith@plexus"
# }
######################################


######################################
# GET http://localhost:8888/
######################################


######################################
# GET http://localhost:8888/customer
# Accept application/json
######################################


######################################
# GET http://localhost:8888/customer/
# Accept application/json
######################################


#########################################
# GET http://localhost:8888/customer/100
#########################################


#########################################
# GET http://localhost:8888/customer/500
#########################################


############################################
# DELETE http://localhost:8888/customer/1
############################################
#curl -X DELETE http://localhost:8888/customer/1

############################################
# DELETE http://localhost:8888/customer/2
############################################
#curl -X DELETE http://localhost:8888/customer/2
